### ISSUE TITLE
Accept recurring payment (subscriptions)?

### ISSUE THREAD

**Issue by diego-pascual** [naoufal/react-native-payments#29] opened 2017-10-26 10:45 UTC

**Comment by Andreyco** [comment] 2017-10-26 16:47
It is already possible, at least for Braintree. Once, you receive nonce pass it to server and handle payment.

**Comment by Andreyco** [comment] 2017-10-28 21:40
Regarding Apple Pay...
https://articles.braintreepayments.com/guides/payment-methods/apple-pay

> **Recurring billing and vaulting**
> Apple Pay cards can be vaulted and used for recurring billing or split shipment transactions. If you plan to use Apple Discover cards for these purposes, you must first contact Discover directly to obtain the proper permissions.

**Comment by Andreyco** [comment] 2017-10-28 23:12
Once again, I can confirm.
You have to use a processor, Braintree or Stripe.

Here is flow I used with Braintree. Since it's not one-time payment, it's a bit complicated and requires several extra steps.

1. receive payment token from Apple Pay. This is `paymentMethodNonce` for Braintree.

Since you cannot use `paymentMethodNonce` for subscriptions here, extra steps are needed.

2. Create a customer
```js
gateway.customer.create({
    // payload
});
```
3. For your customer, create payment method with received `paymentMethodNonce`.
```js
gateway.paymentMethod.create({
    customerId: 'id'
    paymentMethodNonce:  'paymentToken received from Apple Pay'
});
```
4. Finally, create subscription with payment method created in previous step.
```js
gateway.subscription.create({
    paymentMethodToken: 'payment method id from previous step'
    planId: "plan name",
    // extra payload if needed, e.g to override price, ...
});
```

**Comment by Andreyco** [comment] 2017-12-05 13:59
Valid reply provided, closing.

**Closed by Andreyco** 2017-12-05 13:59 UTC
Labels: question

**Comment by Andreyco** [comment] 2018-07-05 12:35
Server side, using oficial Sdk. Sole function of React Native Payment is to present UI, get user info and payment token for you. Processing payment is out of scope of this package - you are responsible for handling this.

**Comment by VietChaien** [comment] 2018-11-27 08:03
> Once again, I can confirm.
> You have to use a processor, Braintree or Stripe.
> 
> Here is flow I used with Braintree. Since it's not one-time payment, it's a bit complicated and requires several extra steps.
> 
> 1. receive payment token from Apple Pay. This is `paymentMethodNonce` for Braintree.
> 
> Since you cannot use `paymentMethodNonce` for subscriptions here, extra steps are needed.
> 
> 1. Create a customer
> 
> ```js
> gateway.customer.create({
>     // payload
> });
> ```
> 
> 1. For your customer, create payment method with received `paymentMethodNonce`.
> 
> ```js
> gateway.paymentMethod.create({
>     customerId: 'id'
>     paymentMethodNonce:  'paymentToken received from Apple Pay'
> });
> ```
> 
> 1. Finally, create subscription with payment method created in previous step.
> 
> ```js
> gateway.subscription.create({
>     paymentMethodToken: 'payment method id from previous step'
>     planId: "plan name",
>     // extra payload if needed, e.g to override price, ...
> });
> ```

Hi @Andreyco , do you know how to integrate subscribe with trial period by ApplePay. Apple Pay require amount > 0 => i can't do it :( please help me

**Comment by dengue8830** [comment] 2019-05-10 00:09
so this lib can't subscribe to apple product subscription that i create from itunes?

**Comment by AdamZaczek** [comment] 2019-05-26 17:50
@dengue8830 It can't. You can use https://github.com/chirag04/react-native-in-app-utils for this purpose.
