### ISSUE TITLE
Exception 'Application tried to present a nil modal view controller on target <UIViewController: 0x1037136a0>.' was thrown while invoking show on target ReactNativePayments with params (     3771 )

### ISSUE THREAD

**Issue by peterhoang064** [naoufal/react-native-payments#54] opened 2017-12-21 08:24 UTC
My environment:
"react-native": "^0.50.3",
"react-native-payments": "^0.3.1",
Xcode: 9.1
Can anyone please help me?

**Comment by Andreyco** [comment] 2017-12-22 09:40
Duplicate of #24 
If you think issue is not duplicate, provide more info.

**Closed by Andreyco** 2017-12-22 09:40 UTC
