### ISSUE TITLE
Error with gateways

### ISSUE THREAD

**Issue by zachheine** [naoufal/react-native-payments#19] opened 2017-09-18 07:09 UTC
`canOpenURL: failed for URL: "com.venmo.touch.v2://x-callback-url/vzero/auth" - error: "This app is not allowed to query for scheme com.venmo.touch.v2"`

![image](https://user-images.githubusercontent.com/826305/30531848-9cb2661a-9c05-11e7-90b8-e13a77d62011.png)

**Comment by zachheine** [comment] 2017-09-18 07:23
Same error with Stripe...

**Comment by naoufal** [comment] 2017-09-18 21:08
I'm in vacation at the moment, so won't be much help until I return. But my gut tells me that the Stripe and/or Braintree frameworks aren't linked properly. 

How did you link the frameworks?  Sure you follow the guides on the add-on READMEs? If so, what does `NativeModules.ReactNativePayments.supportedGateways` return when called from your app. 

Also now sure what the code snippet refers to? Where does `canOpenUrl` come from?

A lot of questions I know, but it's hard to help with the little context provide. The more detail you can add the better.

**Comment by zachheine** [comment] 2017-09-19 14:48
I followed the guides but will go back through and try again (to see about the linking). When I was running on the device through the terminal, I would hit the link to "Buy with Braintree" and the app would crash.  I then opened in Xcode and ran from there.  That was the where I got the `canOpenURL` logging from above, plus the screenshot.

**Comment by naoufal** [comment] 2017-09-19 15:11
What happens when you call the supportedGateways method?

**Comment by zachheine** [comment] 2017-09-24 22:16
When I call `NativeModules.ReactNativePayments.supportedGateways` I get `stripe`.

Tried starting a project from scratch.  Getting a new error now:

`Exception 'Application tried to present a nil modal view controller on target <UIViewController: 0x100c10620>.' was thrown while invoking show on target ReactNativePayments with params (
    311
)`

**Comment by naoufal** [comment] 2017-09-27 16:55
@zachheine What version of React Native, iOS, XCode and react-native-payments are you running?

**Comment by naoufal** [comment] 2017-09-27 16:56
> When I was running on the device through the terminal, I would hit the link to "Buy with Braintree" and the app would crash. 

Are you referring to the braintree example or is this your own app?

**Comment by markrickert** [comment] 2017-10-02 18:33
@naoufal I'm getting this same issue... I followed the examples exactly and the braintree component is linked.

React Native: `0.48.2`
yarn: `1.1.0`
node: `8.6.0`
watchman: `4.9.0`

When looking in the `Frameworks` folder in the xcode project, i can see that both projects that it linked aren't available. When right clicking and selecting "Show in Finder", I get nothing.

![screen shot 2017-10-02 at 12 23 48 pm](https://user-images.githubusercontent.com/139261/31092761-a6a21662-a76c-11e7-8c47-01e76828626e.jpg)

When hitting the ApplePay button it fires off this code:

```js
  buyWithApplePay = () => {
    // Apple pay configuration
    const METHOD_DATA = [{
      supportedMethods: ['apple-pay'],
      data: {
        merchantIdentifier: 'merchant.com.mycompany.propersandboxmerchantid',
        supportedNetworks: ['visa', 'mastercard', 'amex'],
        countryCode: 'US',
        currencyCode: 'USD',
        paymentMethodTokenizationParameters: {
          parameters: {
            gateway: 'braintree',
            'braintree:tokenizationKey': 'sandbox_asdfasdfasdfasdfasdf', // <- this is a real token in my code
          },
        },
      },
    }]
    // Details
    const DETAILS = {
      id: 'basic-example',
      displayItems: [
        {
          label: 'Fifty Dollar Thing',
          amount: { currency: 'USD', value: '49.99' },
        },
      ],
      total: {
        label: 'Test Merchant Name',
        amount: { currency: 'USD', value: '49.99' },
      },
    }

    const paymentRequest = new PaymentRequest(METHOD_DATA, DETAILS)
    paymentRequest.show().then(paymentResponse => {
      console.log('We got a payment response from applepay')
      console.log(paymentResponse)
    })
    
  }
```

then Xcode gives me this screen:

![screen shot 2017-10-02 at 12 25 00 pm](https://user-images.githubusercontent.com/139261/31092921-38ebbfbe-a76d-11e7-98de-8b243fa6b166.jpg)


I also tried adding `com.venmo.touch.v2` to the `Info.plist`'s `LSApplicationQueriesSchemes` array to no avail. Still get that same error.

Calling `NativeModules.ReactNativePayments.supportedGateways` right before the call to `show()` results in:

```js
["braintree"]
```

Has anyone figured out what's going on here yet?

**Comment by markrickert** [comment] 2017-10-02 18:44
Update: I just manually linked `BraintreeCore.framework` and `BraintreeApplePay.framework` so that they're no longer red and are pointing to the correct place and i'm still getting this error.

```
-canOpenURL: failed for URL: "com.venmo.touch.v2://x-callback-url/vzero/auth" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
```

**Comment by markrickert** [comment] 2017-10-02 19:18
Moving the line where it crashes down to the bottom of that array:

```objective-c
    NSDictionary *supportedNetworksMapping = @{
        @"amex": PKPaymentNetworkAmex,
        @"chinaunionpay": PKPaymentNetworkChinaUnionPay,
        @"discover": PKPaymentNetworkDiscover,
        @"mastercard": PKPaymentNetworkMasterCard,
        @"privatelabel": PKPaymentNetworkPrivateLabel,
        @"visa": PKPaymentNetworkVisa,
        @"interac": PKPaymentNetworkInterac,
        @"suica": PKPaymentNetworkSuica,
        @"quicpay": PKPaymentNetworkQuicPay,
        @"idcredit": PKPaymentNetworkIDCredit,
        @"jcb": PKPaymentNetworkJCB
    };
```

and now it crashes on `@"suica": PKPaymentNetworkSuica,`

---

I've also tried commenting out the braintree section of the `METHOD_DATA` (`paymentMethodTokenizationParameters` section) and I get the same issue.

---

## I guess this is progress?

After changing the dictionary to be just amex, discover, visa, and mastercard, i'm seeing a new error.

```objective-c
    NSDictionary *supportedNetworksMapping = @{
        @"amex": PKPaymentNetworkAmex,
        @"discover": PKPaymentNetworkDiscover,
        @"mastercard": PKPaymentNetworkMasterCard,
        @"visa": PKPaymentNetworkVisa
    };
```

![img_8520](https://user-images.githubusercontent.com/139261/31094814-a903b5e4-a773-11e7-9380-c8fe96ffa2dd.PNG)

**Comment by markrickert** [comment] 2017-10-02 22:37
OK, so I dod some more digging and found that if you don't have ApplePay set up properly with one card in it and VERIFIED, trying to create a `PKPaymentAuthorizationViewController` will return `nil`. I also didn't have my braintree applepay certificate in my local keychain, so I added that.

I also noticed an error message in my xcode log something like:

> This device can not use Apple Pay

But I have it working now!

This stackoverflow question and a few of the answers helped me a lot: https://stackoverflow.com/questions/26476469/applepay-ios-error-this-device-cannot-make-payments

ApplePay sandbox setup instructions: https://developer.apple.com/support/apple-pay-sandbox/

I think i've got it solved, but still not sure why  the app was crashing with the full `supportedNetworksMapping` dictionary.

**Comment by Andreyco** [comment] 2017-10-30 12:44
Guys, original payment network error is caused by different iOS versions. Not all payment networks are available on all iOS version. See related PR for fix.

**Comment by jcampalo** [comment] 2017-11-30 20:48
I get the same error on iOS 9 and previous versions, it seems that there is a problem when getting `supportedNetworksMapping` on older versions, it could be fixed with another check.

**Comment by Andreyco** [comment] 2018-01-15 21:35
@zachheine could you please checkout v0.4.0? Some the issues could be resolved already.

**Comment by iM-GeeKy** [comment] 2018-01-21 22:21
When trying to make the PaymentRequest globally available, I am receiving the following error.
![screen shot 2018-01-21 at 5 12 16 pm](https://user-images.githubusercontent.com/7604441/35199599-40db5d98-fece-11e7-9fd2-6e2c3cece806.png)
I've downloaded the package and linked the native dependencies as well as set up Apple Pay following the documentation provided. Any ideas on this? I'm up to date on all of my versions/packages.

**Closed** 2018-05-10 22:53 UTC
