### ISSUE TITLE
How card adding screen looks?

### ISSUE THREAD

**Issue by henrikra** [naoufal/react-native-payments#65] opened 2018-01-25 13:02 UTC
I am currently using tipsi-stripe with my app. https://github.com/tipsi/tipsi-stripe

I am curious how the card adding screen looks with this library when using Stripe. For example with tipsi-stripe it looks like this https://github.com/tipsi/tipsi-stripe#example-4

Also is it possible to localize your card adding screen?

**Comment by Andreyco** [comment] 2018-01-25 22:05
Duplicate of #60 
Please, see #60 for more info

**Closed by Andreyco** 2018-01-25 22:05 UTC
